name: gallery
description: Nothing Gallery
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2

  # setting highest refresh rate
  flutter_displaymode: ^0.6.0

  # update ui without setstate
  provider: ^6.0.5
  
  # saving preferences
  shared_preferences: ^2.2.2
  
  # to ask and check permissions
  permission_handler: ^11.0.1
  
  # get entitites and path
  photo_manager: ^2.7.2

  # view photo and play video
  photo_view: ^0.14.0
  video_player: ^2.7.2
  chewie: ^1.7.1

  # dateTime format
  intl: ^0.18.1

  # share entities on different apps
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: dotmatrix
      fonts:
        - asset: assets/fonts/DOTMATRX.TTF